apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-controle-temperatura
  labels:
    app: controle-temperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: controle-temperatura
  template:
    metadata:
      labels:
        app: controle-temperatura
    spec:
      containers:
        - name: controle-temperatura
          image: dknunes/controle-temperatura:v1
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: svc-controle-temperatura
spec:
  type: NodePort
  selector:
    app: controle-temperatura
  ports:
     - port: 8080
       nodePort: 30000
